name: "Dependency-Check"

on: 
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt install npm
          sudo npm install --package-lock
          npm audit fix

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
        

      - name: Upload test result
        uses: actions/upload-artifact@v2
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports